from __future__ import annotations

"""
Legal and data-handling notices.

Kept in one module so the wording shown in the sidebar, the wording shown at
upload, and the wording written into exports cannot drift apart. The long-form
version lives in `LEGAL.md`.

The substantive risk this addresses is not the upload itself. It is that the
full text of a paper — frequently a subscription or pay-per-view article — is
transmitted to a third-party LLM API, and on the hosted deployment also passes
through the hosting provider's servers. Publisher licences commonly permit
personal research use while restricting systematic downloading and disclosure
to third parties, and sending licensed full text to a commercial API is
plausibly outside them. Users deserve to be told that in the moment they are
about to do it, not in a document they will never open.

None of this is legal advice, and the notices below have not been reviewed by
counsel. Institutions deploying this tool should have their own legal and
research-integrity people read them.
"""

__all__ = [
    "LEGAL_SUMMARY_MD",
    "CLOUD_TRANSFER_WARNING",
    "LOCAL_PROCESSING_NOTE",
    "UPLOAD_ACKNOWLEDGEMENT",
    "EXPORT_DISCLAIMER",
    "SCIENTIFIC_DISCLAIMER",
    "with_disclaimer",
]


#: Shown when a cloud provider is selected and PDFs have been uploaded.
CLOUD_TRANSFER_WARNING = (
    "**The full text of these PDFs will be sent to {provider}.** Selected "
    "passages of each paper leave this machine and are transmitted to a "
    "third-party API for processing.\n\n"
    "Many publisher subscription licences permit personal research use but "
    "restrict systematic downloading and disclosure of licensed content to "
    "third parties. If any of these papers is behind a paywall or covered by "
    "an institutional licence, check that agreement before continuing — or "
    "switch the Stage 2 provider to **Ollama (local)**, which processes the "
    "paper entirely on this machine and sends nothing outward."
)

#: Shown when the local provider is selected, so the safe path is legible too.
LOCAL_PROCESSING_NOTE = (
    "Stage 2 is set to local Ollama: paper text is processed on this machine "
    "and is not sent to any third-party API."
)

#: Shown beneath the uploader. Phrased as a statement of what proceeding
#: means rather than as a consent gate — the point is that the user reads it
#: at the moment it applies, not that they are made to click through it.
UPLOAD_ACKNOWLEDGEMENT = (
    "By continuing you confirm you have lawful access to these papers and "
    "accept responsibility for complying with their publisher and "
    "institutional terms."
)

#: One line, written into every export so a file that leaves the app carries
#: its own caveat.
EXPORT_DISCLAIMER = (
    "Generated by AI4AOP KER extractor. Machine-extracted from the cited "
    "sources and NOT validated by an expert. Contains short verbatim "
    "quotations reproduced from copyrighted works for the purpose of "
    "citation; reuse is the recipient's responsibility."
)

SCIENTIFIC_DISCLAIMER = (
    "This tool produces machine-extracted candidate Key Events and Key Event "
    "Relationships. Quote verification confirms that a sentence exists in the "
    "source document — it does not confirm that the relationship inferred from "
    "it is correct. Output is not suitable for regulatory submission without "
    "expert review."
)

LEGAL_SUMMARY_MD = f"""
**Your papers.** You are responsible for having lawful access to everything you
upload, and for complying with the publisher and institutional terms that cover
it. This tool does not circumvent access controls and does not obtain papers on
your behalf.

**Where your papers go.** With **Ollama (local)** selected, paper text is
processed on this machine and never leaves it. With **Anthropic** or **OpenAI**
selected, the selected passages of each paper are transmitted to that provider's
API for processing, and on the hosted deployment the uploaded file also passes
through the hosting provider's servers. Review the provider's data-usage terms,
and prefer the local option for subscription content.

**What is stored.** Extractions, quotations, curation decisions and run
manifests are written to the local `aop_rag.db` file. Uploaded PDFs themselves
are not retained after processing. Nothing is redistributed or published by the
tool.

**Quotations and exports.** Extracted evidence includes short verbatim
quotations from the source papers, reproduced so that a claim can be checked
against its source. Exports carry these quotations with them; how you reuse or
share an export is your responsibility.

**Third-party data.** PubMed/E-utilities, AOP-Wiki and the EBI OLS4 service
each carry their own terms of use and attribution requirements. Check and
attribute them in any publication derived from this output.

**No warranty.** {SCIENTIFIC_DISCLAIMER}

*These notices are provided for transparency and are not legal advice. If you
are deploying this tool at an institution, have your legal and research
integrity offices review them.*
"""


def with_disclaimer(text: str, *, comment: str = "#") -> str:
    """
    Prefix an export with the disclaimer as a comment line.

    A file that leaves the app arrives somewhere with no surrounding context —
    a shared drive, an email, a supplementary materials bundle — so the caveat
    has to travel inside the file rather than beside it.
    """
    return f"{comment} {EXPORT_DISCLAIMER}\n{text}"
